### ISSUE TITLE
Final evaluation matrices

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Dataset#16]
1. Generate one resulting matrix (issue #15) for all percentages tested (for AC and for AN)
2. Create two new matrices, one for AC and one for AN. These matrix must have:
- row 1 - first line of the matrix for test with 10% input
- row 2 - first line of the matrix for test with 20% input
- row 3 - first line of the matrix for test with 30% input
- (...)
- row 9 - first line of the matrix for test with 90% input

The number of columns will be 15, because this is the number of columns of the resulting matrix generated on issue #15.

I.e., the amount of lines that the resulting matrix will have is the same amount of percentages tested and each line is going to be the first line of the matrix resulting from the evaluation performed on issue #15.

**Comment by mozzherina** [comment]
[matrixes_an.csv](https://github.com/unibz-core/Scior-Dataset/files/10582540/matrixes_an.csv)
[matrixes_ac.csv](https://github.com/unibz-core/Scior-Dataset/files/10582541/matrixes_ac.csv)
