### ISSUE TITLE
Dataset with incomplete data

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Dataset#17]
@mozzherina, I found out that some datasets do not have all their information available in the catalog folder. For example, check https://github.com/unibz-core/Scior-Dataset/tree/main/catalog/amaral2019rot, which has missing taxonomy and data files.

Please upload the data that is absent.

**Comment by mozzherina** [comment]
@pedropaulofb, hope it's fixed. Please, check.
