### ISSUE TITLE
Query (Selection): Taxonomies with more than MINIMUM_ALLOWED_NUMBER_CLASSES

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Dataset#7]
Considering that MINIMUM_ALLOWED_NUMBER_CLASSES = 20,

Which are the taxonomies that have more classes than MINIMUM_ALLOWED_NUMBER_CLASSES?

Please attach a file containing the taxonomies' names.

**Comment by mozzherina** [comment]
Done
