### ISSUE TITLE
Usefulness Analysis for the Tool's Objective: CLASSIFICATIONS Inferred knowledge

### ISSUE THREAD

**Issue by pedropaulofb** [unibz-core/OntCatOWL-Dataset#9]
Considering only valid taxonomies, which are the ones that:

do not have inconsistencies
do not have divergences
have more than MINIMUM_ALLOWED_NUMBER_CLASSES classes that are not classified as "other"

please plot 2 line graphs (for ac and for an execution modes) with **2 lines** each. Verify the necessity to plot error bars.

**Plotted Lines:**
- Line A: percentage of known classifications used as input (range from PERCENTAGE_INITIAL to PERCENTAGE_FINAL). This may be a straight line. 
  - Use the column `classif_b_known_classif_types_p`.
- Line B: percentage of known classifications after the execution (result). These will probably be a "curve". 
  - Use the column `classif_a_known_classif_types_p`.

Both variables are found in the `statistics_XXX_tt002_MM_txYYY.csv` file.

Use the average of values of all executions of all these 3 sets of taxonomies (NUMBER_OF_EXECUTIONS_PER_DATASET_PER_PERCENTAGE).

**Axis:**
- Y axis: percentage of known classifications (i.e., percentage of known knowledge). For types, 14*number_of_classes correspond to 100 %.
- X axis: percentage of classes used as input (from PERCENTAGE_INITIAL to PERCENTAGE_FINAL, increasing PERCENTAGE_RATE)

**Calculate:**
- On average, with how much input we can reach 100% of known classifications?
- Which is the most efficient and the most inefficient percentage of input concerning inferred classifications?
  - Most efficient: corresponds to the highest difference between plotted line A and each one of B lines.
  - Most efficient: corresponds to the lowest difference between both plotted line A and each one of B lines.
  - Please generate a table with values of differences between input and output percentages (lines A and B) for all tested percentages.

**Comment by pedropaulofb** [comment]
Question that we can answer with this information:
- For each different taxonomy size, in average with how much input we can reach 100% of known classifications?

**Comment by pedropaulofb** [comment]
Reevaluate this issue after analyzing the `taxonomies.csv` file to be created (Tester's [issue #20](https://github.com/unibz-core/OntCatOWL-Tester/issues/20)).

**Comment by pedropaulofb** [comment]
@mozzherina, after this analysis, please go to issue #14.

**Comment by pedropaulofb** [comment]
@mozzherina, the valid taxonomies are the ones listed in the file that I attached to the issue #14. Please check it there.

**Comment by mozzherina** [comment]
![image](https://user-images.githubusercontent.com/39998083/213882537-5f031805-ca42-4790-84a9-a96ba50c482e.png)

**Comment by mozzherina** [comment]
![image](https://user-images.githubusercontent.com/39998083/213882595-188b883d-317f-493c-8afb-0a08ca6966f2.png)

**Comment by mozzherina** [comment]
![image](https://user-images.githubusercontent.com/39998083/213882698-15f6e7e0-c931-4b65-85b0-2ac85a56d4fe.png)

**Comment by pedropaulofb** [comment]
@mozzherina, the graphs are using the wrong variables. Please regenerate them using:

line **INITIAL**: `classif_b_known_classif_types_p`
line **FINAL**: `classif_a_known_classif_types_p`

You can find both in the file `statistics_XXX_tt002_MM_txYYY.csv`

I also added this information to the original request in this issue.

**Comment by mozzherina** [comment]
[is9_ac.csv](https://github.com/unibz-core/Scior-Dataset/files/10481272/is9_ac.csv)
![is9_ac](https://user-images.githubusercontent.com/39998083/214083160-9279b438-adf7-4d2c-bd84-140ca33bb01d.png)
[is9_an.csv](https://github.com/unibz-core/Scior-Dataset/files/10481273/is9_an.csv)
![is9_an](https://user-images.githubusercontent.com/39998083/214083167-1904dc02-7be9-46ef-897d-3deb97283382.png)
